"""add category active index

Revision ID: 88adce94a1b2
Revises: c631e8dd1068
Create Date: 2026-09-27 01:16:28.183865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88adce94a1b2'
down_revision: Union[str, Sequence[str], None] = 'c631e8dd1068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    # ### end Alembic commands ###
